version: '3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.0.0


    environment:
    ## This set of env should be used only for initial setup/debugging
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ##
      GF_USERS_DEFAULT_THEME: "light"
      GF_INSTALL_PLUGINS: "flant-statusmap-panel, https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.4.0/victoriametrics-datasource-v0.4.0.zip;victoriametrics-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victoriametrics-datasource"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/mikrotik/mikrotik_mktxp_exporter.json

    #to avoid dns blocks for plugins 
    dns:
      - 1.1.1.1

    restart: always

    ports:
      - "3000:3000/tcp"

    volumes:
    - metric-stack_grafanadata:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    #- ./victoriametrics-datasource:/var/lib/grafana/plugins/grafana-datasource
    

volumes:
  grafanadata: {}
