scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']
  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']
  - job_name: 'loki'
    static_configs:
      - targets: ['192.168.88.195:3100']
  - job_name: 'fluent-bit'
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
      - targets: ['fluent-bit:2020']
